INSERT INTO `flavors` (`id`, `flavor_name`) VALUES (1, 'Trái Cây');
INSERT INTO `flavors` (`id`, `flavor_name`) VALUES (2, 'Socola');
INSERT INTO `flavors` (`id`, `flavor_name`) VALUES (3, 'Dâu Tây');
INSERT INTO `flavors` (`id`, `flavor_name`) VALUES (4, 'Vanilla');
INSERT INTO `flavors` (`id`, `flavor_name`) VALUES (5, 'Matcha');
INSERT INTO `flavors` (`id`, `flavor_name`) VALUES (6, 'Caramel');
INSERT INTO `flavors` (`id`, `flavor_name`) VALUES (7, 'Dừa');
INSERT INTO `flavors` (`id`, `flavor_name`) VALUES (8, 'Cam');
INSERT INTO `flavors` (`id`, `flavor_name`) VALUES (9, 'Chanh');
INSERT INTO `flavors` (`id`, `flavor_name`) VALUES (10, 'Mâm Xôi');
INSERT INTO `flavors` (`id`, `flavor_name`) VALUES (11, 'Cà Phê');
INSERT INTO `flavors` (`id`, `flavor_name`) VALUES (12, 'Dứa');
INSERT INTO `flavors` (`id`, `flavor_name`) VALUES (13, 'Chanh Leo');
INSERT INTO `flavors` (`id`, `flavor_name`) VALUES (14, 'Dưa Hấu');
INSERT INTO `flavors` (`id`, `flavor_name`) VALUES (15, 'Bơ Đậu Phộng');
INSERT INTO `flavors` (`id`, `flavor_name`) VALUES (16, 'Hoa Hồng');
INSERT INTO `flavors` (`id`, `flavor_name`) VALUES (17, 'Mật Ong');
INSERT INTO `flavors` (`id`, `flavor_name`) VALUES (18, 'Bắp');
INSERT INTO `flavors` (`id`, `flavor_name`) VALUES (19, 'Hạnh Nhân');
